baseurl = "https://echo.labstack.com"
languageCode = "en-us"
canonifyurls = true
googleAnalytics = "UA-85059636-2"
[permalinks]
  guide = "/guide/:filename"
  middleware = "/middleware/:filename"
  example = "/cookbook/:filename"

[languages]
[languages.en]
  title = "Echo - High performance, minimalist Go web framework"
[languages.en.params]
  description = "Echo is a high performance, extensible, minimalist web framework for Go (Golang)."

[languages.cn]
  title = ""
[languages.cn.params]
  description = ""
